name: crud_firebase
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  firebase_core: ^2.25.3
  flutter:
    sdk: flutter

  go_router: ^13.1.0
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.4.10
  formz: ^0.6.1
  flutter_dotenv: ^5.1.0
  dio: ^5.4.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/employee.png
    - .env
